### ISSUE TITLE
有些小错误可以改一下 File "main.py", line 269     f.      ^ SyntaxError: invalid syntax 

### ISSUE THREAD

**Issue by QGB** [wingood-xu/suspendLyric#2]
我用的python3.7运行的

```
python main.py
  File "main.py", line 269
    f.
     ^
SyntaxError: invalid syntax


Traceback (most recent call last):
  File "main.py", line 289, in <module>
    qss = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 130: illegal multibyte sequence

```

**Comment by QGB** [comment]
‘’‘
Traceback (most recent call last):
  File "main.py", line 264, in paintEvent
    self.drawText(event,painter)
  File "main.py", line 271, in drawText
    qp.setFont()
TypeError: setFont(self, QFont): not enough arguments
’‘’
